[2017-08-08 09:49:48,028] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0946ca69-6cd7-4d51-9cac-504de4cdc8a4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 09:51:37,107] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0946ca69-6cd7-4d51-9cac-504de4cdc8a4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 09:52:07,252] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0946ca69-6cd7-4d51-9cac-504de4cdc8a4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 09:52:28,314] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0946ca69-6cd7-4d51-9cac-504de4cdc8a4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 09:54:15,965] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 0946ca69-6cd7-4d51-9cac-504de4cdc8a4 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:07:08,831] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 16a7583a-5959-4dcd-9d3b-1ee4db5c092f failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Delete existing data from target table; Error Code=-1073548784; Error Description=Executing the query "delete from [dbo].[tblFactLoan] where DimReporting..." failed with the following error: "Incorrect syntax near the keyword 'and'.". Possible failure reasons: Problems with the query, "ResultSet" property not set correctly, parameters not set correctly, or connection not established correctly.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:07:54,315] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 30004802-b294-420f-8fef-2535856e46d0 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Delete existing data from target table; Error Code=-1073548784; Error Description=Executing the query "delete from [dbo].[tblFactLoan] where DimReporting..." failed with the following error: "Incorrect syntax near the keyword 'and'.". Possible failure reasons: Problems with the query, "ResultSet" property not set correctly, parameters not set correctly, or connection not established correctly.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:22:29,774] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 9282457f-a0ae-421e-92da-d771227aca6c failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at VerifyPaymentFile.Verify.verifyPaymentFile(String excelFilePath)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:23:49,956] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 9282457f-a0ae-421e-92da-d771227aca6c failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at VerifyPaymentFile.Verify.verifyPaymentFile(String excelFilePath)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:24:21,947] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 777b79c9-8b11-43d0-9a33-f6ff8167083b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at VerifyPaymentFile.Verify.verifyPaymentFile(String excelFilePath)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:25:57,227] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 777b79c9-8b11-43d0-9a33-f6ff8167083b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at VerifyPaymentFile.Verify.verifyPaymentFile(String excelFilePath)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-08 10:27:42,924] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 777b79c9-8b11-43d0-9a33-f6ff8167083b failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Cannot find table 0.
   at System.Data.DataTableCollection.get_Item(Int32 index)
   at VerifyPaymentFile.Verify.verifyPaymentFile(String excelFilePath)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
