[2017-08-19 07:38:19,954] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 560173da-789b-4ecd-849e-e2faed5af783 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.OleDb.OleDbException: External table is not in the expected format.
   at AssetTemplate.AssetTemplateVerificator.CreateWorkingSchema(String excelFilePath, String connectionString, String tableName, String schema)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-19 07:38:29,633] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 560173da-789b-4ecd-849e-e2faed5af783 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.OleDb.OleDbException: External table is not in the expected format.
   at AssetTemplate.AssetTemplateVerificator.CreateWorkingSchema(String excelFilePath, String connectionString, String tableName, String schema)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-19 07:38:42,613] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 560173da-789b-4ecd-849e-e2faed5af783 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.OleDb.OleDbException: External table is not in the expected format.
   at AssetTemplate.AssetTemplateVerificator.CreateWorkingSchema(String excelFilePath, String connectionString, String tableName, String schema)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-19 07:40:34,628] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for d6479921-f589-4c24-8b43-3fc2bcb4b5d0 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.OleDb.OleDbException: 'PoolCut$' is not a valid name. Make sure that it does not include invalid characters or punctuation and that it is not too long.
   at AssetTemplate.AssetTemplateVerificator.CreateWorkingSchema(String excelFilePath, String connectionString, String tableName, String schema)
   --- End of inner exception stack trace ---
   at BL.TaskProcessService.OperationProvider.RunManagedMethod(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-19 07:42:28,958] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 33465605-5c14-4288-96ce-e2aa9edeff49 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
[2017-08-19 07:42:40,397] ERROR Securitisation.Utilities.Common.Log4NetLogService - Run task for 33465605-5c14-4288-96ce-e2aa9edeff49 failed
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Source=Data Flow Task; Error Code=-1073548540; Error Description=An error occurred with the following error message: "FlexCel.Core.FlexCelCoreException: Sheet does not exist: "PoolCut"
   at FlexCel.Core.FlxMessages.ThrowException(FlxErr ResName, Object[] args)
   at FlexCel.XlsAdapter.XlsFile.GetSheetIndex(String sheetName, Boolean throwException)
   at FlexCel.XlsAdapter.XlsFile.set_ActiveSheetByName(String value)
   at CozyRoc.SqlServer.SSIS.ExcelConnection.GetColumnsCount(String sheet)
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnNames()
   at CozyRoc.SqlServer.SSIS.ExcelSource._GetColumnIdx()
   at CozyRoc.SqlServer.SSIS.ExcelSource.PrimeOutput(Int32 outputs, Int32[] outputIDs, PipelineBuffer[] buffers)".

Source=Data Flow Task; Error Code=-2147467259; Error Description=Attempt to read message string for 0xc02090f5 failed with error 0xc02090f2. Make sure all message related files are registered.
Source=Data Flow Task; Error Code=-1073450952; Error Description=SSIS Error Code DTS_E_PRIMEOUTPUTFAILED.  The PrimeOutput method on Excel Source Plus returned error code 0xC02090F5.  The component returned a failure code when the pipeline engine called PrimeOutput(). The meaning of the failure code is defined by the component, but the error is fatal and the pipeline stopped executing.  There may be error messages posted before this with more information about the failure.


   at BL.TaskProcessService.OperationProvider.RunSSIS(ITaskAction action)
   --- End of inner exception stack trace ---
   at BL.TaskEngine.TaskEngine.RunProcessesByTask()
   at TaskProcessEngine.TaskProcessService.RunTask(Guid sessionId, String applicationDomain) in e:\Dev\SFM\Products\TaskProcessEngine\TaskProcessEngine\TaskProcessService.svc.cs:line 63
